# Generated by Django 3.1.7 on 2021-05-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuarios',
        ),
        migrations.AddField(
            model_name='ventas',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
